### ISSUE TITLE
Build failing : ghc-7.10.3 : Mac osx

### ISSUE THREAD

**Issue by ashishnegi** [bazqux/http-conduit-downloader#5]
Hi
I included your `http-conduit-downloader` in `.cabal` and am using `stack build` to build it.
Since it is not on stackage, it asks me to put `http-conduit-downloader` in `stack.yaml`.

After doing it, and fixing HOpenssl library path issues by adding them to `stack.yaml`, i found that build fails with 

``` haskell
http-conduit-downloader-1.0.25/Network/HTTP/Conduit/Downloader.hs:354
C.checkStatus’ is not a (visible) constructor field name
... and more
```

This is provided by `Data.Default` which in `http-conduit-downloader` does not have any upper/lower bounds. and so it picks up the latest and fails.

Also, `hackage` does not have latest `http-conduit-downloader` as well.

Can you please publish with new `http-conduit-downloader` ?

**Comment by ashishnegi** [comment]
It would be better if you can add `cabal freeze` file as well.

**Comment by vshabanov** [comment]
I've updated downloader for the latest `http-client`.

But there is the problem with abandoned `HsOpenSSL` package. I need `_SSL_set_tlsext_host_name` which I've added in https://github.com/vshabanov/HsOpenSSL and made a pull request https://github.com/phonohawk/HsOpenSSL/pull/40
but @phonohawk ignored it as well as my email with proposition to become a maintainer for HsOpenSSL.

So even if I upload `http-conduit-downloader` to Hackage it still won't build due to outdated `HsOpenSSL`.

**Comment by ashishnegi** [comment]
Can you fork HsOpenSSL and use that as your dependency ?

**Comment by vshabanov** [comment]
I'm afraid there will be linking errors due to duplicated C FFI functions in projects that use both fork and original HsOpenSSL.

**Comment by vshabanov** [comment]
Started a process of becoming a maintainer for HsOpenSSL
https://mail.haskell.org/pipermail/haskell-cafe/2016-September/124999.html
Hope I will be able to upload a fixed HsOpenSSL and http-conduit-downloader in a few weeks.

**Comment by vshabanov** [comment]
I've become HsOpenSSL maintainer, uploaded new HsOpenSSL version and new http-conduit-version which should compile fine with latest http-client.

**Comment by vshabanov** [comment]
And why do you need `cabal freeze`?

**Comment by ashishnegi** [comment]
I thought that problem was with unable to find exact version of dependencies to build. 
`cabal freeze` is better to tell the version of dependencies that author finds right.
